#!/usr/bin/env node
/**
 * Writes `style/palette.css` from `style/palette.mjs`.
 *
 * Tailwind needs the scales as literal CSS custom properties inside `@theme`,
 * and the email templates need the same values as JavaScript strings. Rather
 * than maintaining both by hand, the CSS half is generated and committed, and
 * `--check` (wired into `npm run verify`) fails the build if it has gone stale.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { PALETTE } from "../style/palette.mjs";

const OUTPUT = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "style",
  "palette.css"
);

const render = () => {
  const scales = Object.entries(PALETTE).map(([name, steps]) =>
    Object.entries(steps)
      .map(([step, hex]) => `  --color-${name}-${step}: ${hex};`)
      .join("\n")
  );

  return `/* Generated by scripts/generate-palette.mjs — do not edit.
   Change style/palette.mjs and run \`npm run gen:palette\`. */

@theme {
${scales.join("\n\n")}
}
`;
};

const expected = render();

if (process.argv.includes("--check")) {
  let actual = "";
  try {
    actual = readFileSync(OUTPUT, "utf8");
  } catch {
    actual = "";
  }

  if (actual !== expected) {
    console.error(
      "✖ style/palette.css is out of date — run 'npm run gen:palette'."
    );
    process.exit(1);
  }

  console.log("✓ style/palette.css matches style/palette.mjs");
} else {
  writeFileSync(OUTPUT, expected, "utf8");
  console.log("✓ wrote style/palette.css");
}
