import { getTranslations } from "next-intl/server";
import {
  PHONE_DISPLAY,
  PHONE_HREF,
  whatsappHref,
} from "@/configuration/contact";
import { RESPONSE_HOURS } from "@/configuration/stay";
import { fullName, formatStay } from "@/lib/enquiry/format";
import type { EnquiryInput } from "@/lib/enquiry/schema";
import { brandFooterLines, brandHeader } from "../brand";
import { renderHtml, renderText, type MailDocument, type MailRow } from "../layout";
import { hostInbox, structureName, type OutgoingMail } from "../transport";

/**
 * Sent to the guest in their own language, from the same Gmail account, so a
 * reply lands back in the host's inbox as an ordinary email.
 */
export async function buildGuestAcknowledgementMail(
  enquiry: EnquiryInput
): Promise<OutgoingMail> {
  const t = await getTranslations({
    locale: enquiry.locale,
    namespace: "enquiryEmail",
  });

  const structure = structureName();
  const stay = formatStay(enquiry, enquiry.locale);

  const rows: MailRow[] = [
    stay ? { label: t("labelDates"), value: stay } : null,
    enquiry.guests
      ? { label: t("labelGuests"), value: String(enquiry.guests) }
      : null,
  ].filter((row): row is MailRow => row !== null);

  const doc: MailDocument = {
    lang: enquiry.locale,
    ...brandHeader(),
    preheader: t("preheader", { hours: RESPONSE_HOURS }),
    eyebrow: t("eyebrow"),
    heading: t("heading"),
    intro: [
      t("greeting", { name: fullName(enquiry) }),
      t("received", { hours: RESPONSE_HOURS }),
    ],
    rowsTitle: rows.length ? t("summaryTitle") : undefined,
    rows,
    quote: { label: t("labelMessage"), text: enquiry.message },
    note: t("urgent", { phone: PHONE_DISPLAY }),
    buttons: [
      { label: t("ctaWhatsapp"), href: whatsappHref() },
      {
        label: t("ctaCall", { phone: PHONE_DISPLAY }),
        href: PHONE_HREF,
        variant: "secondary",
      },
    ],
    closing: t("replyable"),
    signOff: t("signature", { structure }),
    footerLines: brandFooterLines(),
    footerNote: t("footerNote"),
  };

  return {
    to: enquiry.email,
    // Without this the reply would go to the sending account, which is not
    // necessarily the inbox the host actually reads.
    replyTo: hostInbox(),
    subject: t("subject", { structure }),
    text: renderText(doc),
    html: renderHtml(doc),
    autoGenerated: true,
  };
}
