import nodemailer, { type Transporter } from "nodemailer";
import { requireEnv } from "@/lib/env";
import {
  EMAIL_LOGO_BASE64,
  EMAIL_LOGO_CID,
  EMAIL_LOGO_FILENAME,
} from "./logo";

/**
 * The only Gmail/nodemailer-specific file. Swapping to Resend (or anything
 * else) once a custom domain exists means rewriting this module and nothing
 * above it.
 */

let cachedTransport: Transporter | null = null;

/** Gmail requires the From address to be the authenticated account. */
export function senderAddress(): string {
  return requireEnv("SMTP_USER");
}

export function hostInbox(): string {
  return process.env.ENQUIRY_TO || senderAddress();
}

export function structureName(): string {
  return process.env.STRUCTURE_NAME || "Il Respiro del Borgo";
}

function getTransport(): Transporter {
  if (!cachedTransport) {
    cachedTransport = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: requireEnv("SMTP_USER"),
        pass: requireEnv("SMTP_APP_PASSWORD"),
      },
    });
  }
  return cachedTransport;
}

export interface OutgoingMail {
  to: string;
  subject: string;
  /** The plain-text alternative. Never omitted: HTML-only mail scores as spam. */
  text: string;
  html: string;
  replyTo?: string;
  /**
   * Marks the message as machine-generated (RFC 3834). Set on acknowledgements
   * so an out-of-office autoresponder on the other side does not reply to it
   * and start a loop.
   */
  autoGenerated?: boolean;
}

export async function sendMail({
  to,
  subject,
  text,
  html,
  replyTo,
  autoGenerated,
}: OutgoingMail) {
  await getTransport().sendMail({
    from: `"${structureName()}" <${senderAddress()}>`,
    to,
    subject,
    text,
    html,
    replyTo,
    // Travels with the message rather than being fetched: `cid:` images are
    // shown by clients that block remote ones, and `inline` keeps the logo out
    // of the attachment list.
    attachments: [
      {
        filename: EMAIL_LOGO_FILENAME,
        content: EMAIL_LOGO_BASE64,
        encoding: "base64",
        cid: EMAIL_LOGO_CID,
        contentDisposition: "inline",
      },
    ],
    headers: autoGenerated
      ? {
          "Auto-Submitted": "auto-replied",
          // Outlook's equivalent of the header above.
          "X-Auto-Response-Suppress": "OOF, AutoReply",
        }
      : undefined,
  });
}
